# Generated by Django 5.2.8 on 2025-11-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(blank=True, default='first_CZsPB4v.jpeg', null=True, upload_to='photos/'),
        ),
    ]
