# Generated by Django 5.2.8 on 2025-11-28 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='news',
            managers=[
            ],
        ),
    ]
