# Generated by Django 5.2.8 on 2025-11-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('bio', models.TextField()),
                ('profile_image', models.ImageField(upload_to='profiles/')),
                ('skills', models.TextField(help_text='Comma-separated skills')),
                ('university', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('graduation_year', models.IntegerField()),
                ('expirence', models.TextField(help_text='Comma-separated experiences')),
                ('social_twitter', models.URLField(blank=True, null=True)),
                ('social_linkedin', models.URLField(blank=True, null=True)),
                ('social_github', models.URLField(blank=True, null=True)),
                ('social_facebook', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
