# Generated by Django 5.2.8 on 2025-11-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='profile_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
