# Generated by Django 5.2.8 on 2025-11-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
