# Generated by Django 5.2.8 on 2025-11-17 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_todo_deadline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
